//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: PluginService.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `PluginService_RouteDefinitionClient`, then call methods of this protocol to make API calls.
public protocol PluginService_RouteDefinitionClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: PluginService_RouteDefinitionClientInterceptorFactoryProtocol? { get }

  func streamHello(
    _ request: PluginService_StreamHelloRequest,
    callOptions: CallOptions?,
    handler: @escaping (PluginService_StreamHelloReply) -> Void
  ) -> ServerStreamingCall<PluginService_StreamHelloRequest, PluginService_StreamHelloReply>
}

extension PluginService_RouteDefinitionClientProtocol {
  public var serviceName: String {
    return "pluginService.RouteDefinition"
  }

  /// Server streaming call to StreamHello
  ///
  /// - Parameters:
  ///   - request: Request to send to StreamHello.
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  public func streamHello(
    _ request: PluginService_StreamHelloRequest,
    callOptions: CallOptions? = nil,
    handler: @escaping (PluginService_StreamHelloReply) -> Void
  ) -> ServerStreamingCall<PluginService_StreamHelloRequest, PluginService_StreamHelloReply> {
    return self.makeServerStreamingCall(
      path: PluginService_RouteDefinitionClientMetadata.Methods.streamHello.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStreamHelloInterceptors() ?? [],
      handler: handler
    )
  }
}

@available(*, deprecated)
extension PluginService_RouteDefinitionClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "PluginService_RouteDefinitionNIOClient")
public final class PluginService_RouteDefinitionClient: PluginService_RouteDefinitionClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: PluginService_RouteDefinitionClientInterceptorFactoryProtocol?
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  public var interceptors: PluginService_RouteDefinitionClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the pluginService.RouteDefinition service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: PluginService_RouteDefinitionClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

public struct PluginService_RouteDefinitionNIOClient: PluginService_RouteDefinitionClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: PluginService_RouteDefinitionClientInterceptorFactoryProtocol?

  /// Creates a client for the pluginService.RouteDefinition service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: PluginService_RouteDefinitionClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol PluginService_RouteDefinitionAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: PluginService_RouteDefinitionClientInterceptorFactoryProtocol? { get }

  func makeStreamHelloCall(
    _ request: PluginService_StreamHelloRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncServerStreamingCall<PluginService_StreamHelloRequest, PluginService_StreamHelloReply>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension PluginService_RouteDefinitionAsyncClientProtocol {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return PluginService_RouteDefinitionClientMetadata.serviceDescriptor
  }

  public var interceptors: PluginService_RouteDefinitionClientInterceptorFactoryProtocol? {
    return nil
  }

  public func makeStreamHelloCall(
    _ request: PluginService_StreamHelloRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncServerStreamingCall<PluginService_StreamHelloRequest, PluginService_StreamHelloReply> {
    return self.makeAsyncServerStreamingCall(
      path: PluginService_RouteDefinitionClientMetadata.Methods.streamHello.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStreamHelloInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension PluginService_RouteDefinitionAsyncClientProtocol {
  public func streamHello(
    _ request: PluginService_StreamHelloRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<PluginService_StreamHelloReply> {
    return self.performAsyncServerStreamingCall(
      path: PluginService_RouteDefinitionClientMetadata.Methods.streamHello.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeStreamHelloInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public struct PluginService_RouteDefinitionAsyncClient: PluginService_RouteDefinitionAsyncClientProtocol {
  public var channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: PluginService_RouteDefinitionClientInterceptorFactoryProtocol?

  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: PluginService_RouteDefinitionClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public protocol PluginService_RouteDefinitionClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'streamHello'.
  func makeStreamHelloInterceptors() -> [ClientInterceptor<PluginService_StreamHelloRequest, PluginService_StreamHelloReply>]
}

public enum PluginService_RouteDefinitionClientMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "RouteDefinition",
    fullName: "pluginService.RouteDefinition",
    methods: [
      PluginService_RouteDefinitionClientMetadata.Methods.streamHello,
    ]
  )

  public enum Methods {
    public static let streamHello = GRPCMethodDescriptor(
      name: "StreamHello",
      path: "/pluginService.RouteDefinition/StreamHello",
      type: GRPCCallType.serverStreaming
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol PluginService_RouteDefinitionProvider: CallHandlerProvider {
  var interceptors: PluginService_RouteDefinitionServerInterceptorFactoryProtocol? { get }

  func streamHello(request: PluginService_StreamHelloRequest, context: StreamingResponseCallContext<PluginService_StreamHelloReply>) -> EventLoopFuture<GRPCStatus>
}

extension PluginService_RouteDefinitionProvider {
  public var serviceName: Substring {
    return PluginService_RouteDefinitionServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "StreamHello":
      return ServerStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<PluginService_StreamHelloRequest>(),
        responseSerializer: ProtobufSerializer<PluginService_StreamHelloReply>(),
        interceptors: self.interceptors?.makeStreamHelloInterceptors() ?? [],
        userFunction: self.streamHello(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public protocol PluginService_RouteDefinitionAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: PluginService_RouteDefinitionServerInterceptorFactoryProtocol? { get }

  func streamHello(
    request: PluginService_StreamHelloRequest,
    responseStream: GRPCAsyncResponseStreamWriter<PluginService_StreamHelloReply>,
    context: GRPCAsyncServerCallContext
  ) async throws
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension PluginService_RouteDefinitionAsyncProvider {
  public static var serviceDescriptor: GRPCServiceDescriptor {
    return PluginService_RouteDefinitionServerMetadata.serviceDescriptor
  }

  public var serviceName: Substring {
    return PluginService_RouteDefinitionServerMetadata.serviceDescriptor.fullName[...]
  }

  public var interceptors: PluginService_RouteDefinitionServerInterceptorFactoryProtocol? {
    return nil
  }

  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "StreamHello":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<PluginService_StreamHelloRequest>(),
        responseSerializer: ProtobufSerializer<PluginService_StreamHelloReply>(),
        interceptors: self.interceptors?.makeStreamHelloInterceptors() ?? [],
        wrapping: { try await self.streamHello(request: $0, responseStream: $1, context: $2) }
      )

    default:
      return nil
    }
  }
}

public protocol PluginService_RouteDefinitionServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'streamHello'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeStreamHelloInterceptors() -> [ServerInterceptor<PluginService_StreamHelloRequest, PluginService_StreamHelloReply>]
}

public enum PluginService_RouteDefinitionServerMetadata {
  public static let serviceDescriptor = GRPCServiceDescriptor(
    name: "RouteDefinition",
    fullName: "pluginService.RouteDefinition",
    methods: [
      PluginService_RouteDefinitionServerMetadata.Methods.streamHello,
    ]
  )

  public enum Methods {
    public static let streamHello = GRPCMethodDescriptor(
      name: "StreamHello",
      path: "/pluginService.RouteDefinition/StreamHello",
      type: GRPCCallType.serverStreaming
    )
  }
}
