// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: PluginService.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamHelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times int32 `protobuf:"varint,1,opt,name=times,proto3" json:"times,omitempty"`
}

func (x *StreamHelloRequest) Reset() {
	*x = StreamHelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PluginService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamHelloRequest) ProtoMessage() {}

func (x *StreamHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PluginService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamHelloRequest.ProtoReflect.Descriptor instead.
func (*StreamHelloRequest) Descriptor() ([]byte, []int) {
	return file_PluginService_proto_rawDescGZIP(), []int{0}
}

func (x *StreamHelloRequest) GetTimes() int32 {
	if x != nil {
		return x.Times
	}
	return 0
}

type StreamHelloReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StreamHelloReply) Reset() {
	*x = StreamHelloReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PluginService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamHelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamHelloReply) ProtoMessage() {}

func (x *StreamHelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_PluginService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamHelloReply.ProtoReflect.Descriptor instead.
func (*StreamHelloReply) Descriptor() ([]byte, []int) {
	return file_PluginService_proto_rawDescGZIP(), []int{1}
}

func (x *StreamHelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_PluginService_proto protoreflect.FileDescriptor

var file_PluginService_proto_rawDesc = []byte{
	0x0a, 0x13, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x22, 0x2a, 0x0a, 0x12, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x22, 0x2c, 0x0a, 0x10, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x68,
	0x0a, 0x0f, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x55, 0x0a, 0x0b, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x12, 0x21, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x30, 0x01, 0x42, 0x0b, 0x5a, 0x09, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_PluginService_proto_rawDescOnce sync.Once
	file_PluginService_proto_rawDescData = file_PluginService_proto_rawDesc
)

func file_PluginService_proto_rawDescGZIP() []byte {
	file_PluginService_proto_rawDescOnce.Do(func() {
		file_PluginService_proto_rawDescData = protoimpl.X.CompressGZIP(file_PluginService_proto_rawDescData)
	})
	return file_PluginService_proto_rawDescData
}

var file_PluginService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_PluginService_proto_goTypes = []interface{}{
	(*StreamHelloRequest)(nil), // 0: pluginService.StreamHelloRequest
	(*StreamHelloReply)(nil),   // 1: pluginService.StreamHelloReply
}
var file_PluginService_proto_depIdxs = []int32{
	0, // 0: pluginService.RouteDefinition.StreamHello:input_type -> pluginService.StreamHelloRequest
	1, // 1: pluginService.RouteDefinition.StreamHello:output_type -> pluginService.StreamHelloReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PluginService_proto_init() }
func file_PluginService_proto_init() {
	if File_PluginService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_PluginService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamHelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PluginService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamHelloReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PluginService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_PluginService_proto_goTypes,
		DependencyIndexes: file_PluginService_proto_depIdxs,
		MessageInfos:      file_PluginService_proto_msgTypes,
	}.Build()
	File_PluginService_proto = out.File
	file_PluginService_proto_rawDesc = nil
	file_PluginService_proto_goTypes = nil
	file_PluginService_proto_depIdxs = nil
}
